---
dist: bionic
sudo: false
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
before_install:
  - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - source /etc/lsb-release && echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable"  | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y influxdb

install:
  - cpanm --quiet --installdeps --notest .

script:
  - prove -v t/
